version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18 # Forces the use of Node.js v18.x
    commands:
      - echo "Using Node.js version 18"
      - npm install

  pre_build:
    commands:
      - echo "Running pre-build phase..."

  build:
    commands:
      - echo "Building the project..."
      - npm run build

  post_build:
    commands:
      - echo "Build complete."
