version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18 # or the runtime of your Lambda function
    commands:
      - cd backend/src
      - echo "Installing dependencies"
      - npm install
      - npm run build

  pre_build:
    commands:
      - echo "Running tests"
      - npm test # Make sure your project has a test script

  build:
    commands:
      - echo "Zipping the Lambda function"
      - zip -r function.zip index.js node_modules/ package.json
  
artifacts:
  files:
    - function.zip
  discard-paths: yes
  base-directory: .



