#!/bin/bash

if [ -z "$1" ]; then
    echo "No command entered"
    exit 1
fi

case "$1" in
    install)
        npm --silent install
        if [ $? -eq 0 ]; then
            echo "Dependencies installed successfully."
        else
            echo "Failed to install dependencies."
            exit 1
        fi
    ;;
    test)
        npm start --silent -- test
    ;;
    *)
        npm start --silent -- $1 $2
esac